/*
    날짜 : 2024/03/06
    이름 : 김형민
    내용 : 3.데이터베이스 개체
*/

-- 실습 3-1 데이터 사전 조회
select * from dic;

select TABLE_NAME FROM USER_TABLES;

select OWNER, TABLE_NAME FROM ALL_TABLES;

SELECT * FROM DBA_TABLES;

SELECT * FROM DBA_USERS;

SELECT * FROM USER_INDEXES;

SELECT * FROM USER_IND_COLUMNS;

CREATE INDEX IDX_USER1_UID ON USER1(`ID`);
SELECT * FROM USER_IND_COLUMNS;

DROP INDEX IDX_USER1_UID;
SELECT * FROM USER_IND_COLUMNS;

-- 실습하기 3-4 뷰 생성/조회/삭제
CREATE VIEW VW_USER1 AS (SELECT NAME, HP, AGE FROM USER1);
CREATE VIEW VW_USER2_AGE_UNDER30 AS (SELECT * FROM USER2 WHERE AGE < 30);
SELECT * FROM USER_VIEWS;

SELECT * FROM VW_USER1;
SELECT * FROM VW_USER2_AGE_UNDER30;

DROP VIEW VW_USER1;
DROP VIEW VW_USER2_AGE_UNDER30;

-- 실습하기 3-5 시퀀시 적용 테이블 생성
CREATE TABLE USER6 (
    SEQ     NUMBER PRIMARY KEY,
    NAME    VARCHAR2(20),
    GENDER  CHAR(1),
    AGE     NUMBER,
    ADDR    VARCHAR2(255)
);

CREATE SEQUENCE SEQ_USER6 INCREMENT BY 1 START WITH 1;

INSERT INTO USER6 VALUES (SEQ_USER6.NEXTVAL, '김유신', 'M', 25, '김해시');
INSERT INTO USER6 VALUES (SEQ_USER6.NEXTVAL, '김춘추', 'M', 23, '경주시');
INSERT INTO USER6 VALUES (SEQ_USER6.NEXTVAL, '신사임당', 'F', 27, '강릉시');

-- 실습하기 4-1 사용자 생성(SYSTEM 접속)
ALTER SESSION SET "_ORACLE_SCRIPT"=true;
CREATE USER gudals8285 IDENTIFIED by 1234;

-- 실습 4-2 사용자 조회
SELECT * FROM ALL_USERS;

-- 실습 4-4 Role 부여
GRANT CONNECT, RESOURCE TO gudals8285;

GRANT UNLIMITED TABLESPACE TO gudals8285;
